### ISSUE TITLE
Consider Show protocol

### ISSUE THREAD

**Issue by pasviegas** [uncomplicate/fluokitten#11]
Hey, I really thing it would be valuable to have a Show protocol

consider de following code

```clojure
(just {:a 2})
;;#<Just uncomplicate.fluokitten.algo.Just@3c6f0c2b>
(show (just {:a 2}))
;;Just {:a 2}
```

Thanks again!

**Comment by blueberry** [comment]
I added toString and print-method for Just and curried functions, so it looks pretty in REPL now.

**Comment by pasviegas** [comment]
Awesome! Thanks! :)
