### ISSUE TITLE
[Q] On inconsistent behavior in doc and 0.6.0 release

### ISSUE THREAD

**Issue by chunsj** [uncomplicate/fluokitten#22]
Hi, I've been toying around fluokitten and which is very fun. However, I found there're some 
inconsistent behaviors between document at [Fluokitten Extensions of Clojure Core](http://fluokitten.uncomplicate.org/articles/clojure_core_extensions.html) and the result.

For example;

The doc says
```clojure
(fmap inc (empty (seq [1]))) => (empty (seq [2]))
(fmap inc (lazy-seq [])) => (lazy-seq [])
```

However, what I got is
```clojure
(fmap inc (empty (seq [1]))) => ()
(fmap inc (lazy-seq [])) => ()
```

Is this correct?

**Comment by blueberry** [comment]
Here is what I got in my repl:

test> (= (lazy-seq []) '())
true
test> (= (empty (seq [2])) '())
true

So, what you got is what is expected. Keep in mind that => is a midje test assignment, not that the repl shoud print (lazy-seq [])...
