### ISSUE TITLE
Enhancement: Consider operadic semantics (convenient composition)

### ISSUE THREAD

**Issue by fithisux** [uncomplicate/fluokitten#25]
(def curried-add4-a (curry add4)) ;; arity 2
(def curried-add4-b (curry add4)) ;; arity 2
(def curried-add4-c (curry add4)) ;; arity 2
(def curried-add4-d (curried-add4-a curried-add4-b curried-add4-c)) ;; arity 4
(def curried-add4-e (curried-add4-a curried-add4-b 5)) ;; arity 3

**Comment by blueberry** [comment]
I'm afraid I don't understand what you are trying to achieve with that code.
